service: cash-control

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 900
  iamRoleStatements:
    - Effect: Allow
      Action:
        - rds-db:connect
      Resource: arn:aws:rds:us-east-1:184440761998:db:pop-dev-instance-1:*

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    minify: true
    external:
      - aws-sdk
      - dotenv
      - pg
      - reflect-metadata
      - typeorm
      - moment
      - moment-timezone
    watch:
      pattern: [ './index.ts', 'src/**/*.ts' ]
      ignore: [ '.serverless/**/*', '.build' ]
  env: ${file(./properties/properties.yaml)}

functions:
  - ${file(./src/functions/reports/index.functions.yml)}
